# Generated by Django 4.1.2 on 2022-10-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_pub', models.IntegerField()),
                ('autores', models.ManyToManyField(related_name='libros', to='home.autor')),
            ],
        ),
    ]
